<a href="https://colab.research.google.com/github/Quntized/Image-Compression-/blob/main/arnoldiiteration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import matplotlib.pyplot as plt
from numpy import linalg as LA
from numpy.linalg import inv

In [4]:
def arnoldi_iteration(A,b,n:int):
  """computes a basis of the (n+1) -krylov subspace of A : the space spanned by (b,Ab,...,A^n b)

  Arguments :
    A :m by m array
    b: initial vector(length m)
    n : dimension of krylov subspace . Must be >=1


  Returns
    Q : m by (n+1) array , the columns are orthonormal basis of the krylov subspace
    h : (n+1) by n array , A on basis Q. It is upper hessenberg."""
  print("A = ",A)
  m = A.shape[0]
  h = np.zeros((n+1,n))
  Q = np.zeros((m,n+1))
  q = b/np.linalg.norm(b)
  print("q = ",q)
  Q[:,0] = q.transpose()
  print("Q = ", Q)

  for k in range(n):
    print('------------------------------')
    print('k = ',k)
    qkp1 = np.dot(A,q)
    print("qkp1 = ",qkp1)
    for j in range(k+1):      #subtract the projection on previous vectors
      h[j,k] = np.dot(Q[:,j].conj(),qkp1)
      print("h[j,k] = ",h[j,k])
      print("Q[:,j]",Q[:,j])
      temp = qkp1.transpose() - h[j,k]*Q[:,j]
      qkp1 = temp.transpose()
      print("v = ",qkp1)
    h[k+1,k] = np.linalg.norm(qkp1)
    eps = 1e-12 #If v is shorter than this threshold , it is the zero vector
    if h[k+1,k]>eps:  # add the produced vector to the list unless the zero vector is produced.
      q = qkp1/h[k+1,k]
      print('q = ',q)
      Q[:,k+1]= q.transpose()
    else: # If that happens stop iterating
      return Q,h
  return Q,h


A = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
b = np.array([[1],[3],[6],[8]])
Q,h = arnoldi_iteration(A,b,3)
print("Q = ",Q)
print("h = ",h)

A =  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
q =  [[0.09534626]
 [0.28603878]
 [0.57207755]
 [0.76277007]]
Q =  [[0.09534626 0.         0.         0.        ]
 [0.28603878 0.         0.         0.        ]
 [0.57207755 0.         0.         0.        ]
 [0.76277007 0.         0.         0.        ]]
------------------------------
k =  0
qkp1 =  [[ 5.43473676]
 [12.2996674 ]
 [19.16459804]
 [26.02952869]]
h[j,k] =  34.85454545454546
Q[:,j] [0.09534626 0.28603878 0.57207755 0.76277007]
v =  [[ 2.11148624]
 [ 2.32991585]
 [-0.77490505]
 [-0.55647544]]
q =  [[ 0.64259332]
 [ 0.70906849]
 [-0.23582858]
 [-0.16935341]]
------------------------------
k =  1
qkp1 =  [[ 0.67583091]
 [ 4.46175017]
 [ 8.24766944]
 [12.03358871]]
h[j,k] =  15.237839384575778
Q[:,j] [0.09534626 0.28603878 0.57207755 0.76277007]
v =  [[-0.77704007]
 [ 0.10313724]
 [-0.46955644]
 [ 0.41062087]]
h[j,k] =  -0.38499461409354374
Q[:,j] [ 0.64259332  0.70906849 -0.23582858 -0.16935341]
v =  [[-0.52964

<ipython-input-4-6d4572bb40b5>:28: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  h[j,k] = np.dot(Q[:,j].conj(),qkp1)
